### ISSUE TITLE
why is the token exposed

### ISSUE THREAD

**Issue by BobMakingPie** [PKBeam/sbhs-hightable#2]
not ok

**Comment by PKBeam** [comment]
because there's no reason for it not to be

**Comment by BobMakingPie** [comment]
someone can look at my computer and access my entire sbhs profile!!!111

**Comment by PKBeam** [comment]
unlucky

**Comment by BobMakingPie** [comment]
legit just set up a quick server to handle that

**Comment by PKBeam** [comment]
nah
